name = "pragma-fortly-dev-worker-rasp-rules"
main = "src/worker.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat_v2"]

[[kv_namespaces]]
binding = "KV_RULES"
id = "583ea681292e4aacb5654af8d03764d5"

[[d1_databases]]
binding = "DB_VIRTUAL_PATCHES"
database_name = "pragma-fortly-dev-d1-rasp-virtual-patches"
database_id = "placeholder-virtual-patches-id"
